TheCSharpAcademy/TCSA.V2026

TCSA.V2026/Components/App.razor
TCSA.V2026/Components/Layout/MainLayout.razor
TCSA.V2026/Program.cs
TCSA.V2026/Services/ThemeService.cs

Initial implementation of dark mode.
NOTES:
- Due to page interactivity, the theme switch does not work in the auth pages.
- Uses cookies to set and retrieve theme
- MudBlazor requires full interactivity to work. So have implemented such in `App.razor`. This may break some things.
- I noted that you prefer no prerendering
**App.razor**
**Light**
**Dark**
**Reflected in Auth**

[Feature] Dark Mode

---

TCSA.V2026/Components/Pages/Dashboard/PeerReviews.razor
TCSA.V2026/Data/DTOs/PeerReviewDisplay.cs
TCSA.V2026/Helpers/PeerReviewHelpers.cs

Added a clickable link to the Title field in Peer Reviews.
Once clicked, the project page will open in a new tab.
Changed the Title column from a `PropertyColumn` to a `TemplateColumn` containing a `MudLink`.
Added the `Href`, which is composed of `project/{projectId}/{projectSlug}`
Added `ProjectSlug` property to `PeerReviewDisplay.cs` DTO
Added `ProjectSlug` initialiser to `PeerReviewHelper.cs`
closes #13 
Thanks,
@chrisjamiecarter 👍

[Feature] Project Link in Peer Reviews

---

TCSA.V2026/Components/Pages/Dashboard/PeerReviews.razor
TCSA.V2026/Helpers/TimeSpanFormatter.cs

This PR improves the "Open Since" column by displaying peer review durations in a more user-friendly format. Additionally, if a peer review project has been open for more than 7 days, the duration text is highlighted in red.
- Added `TimeSpanFormatter` for displaying durations in a human-readable format using the Humanizer library
- Improved the readability of the 'Open Since' column by utilizing the `TimeSpanFormatter`
- Applied conditional styling to the 'Open Since' column to highlight priority for peer review projects open for more than 7 days

feat: add readable peer reviews duration formatting

---

TCSA.V2026/Components/Pages/Dashboard/Leaderboard.razor

This PR adds mobile-responsive styling to the users and reviews leaderboards, ensuring they display correctly on smaller devices.
- Updated `<MudDataGrid>` components to include `Breakpoint="Breakpoint.None"` for consistent responsiveness.   
- Enhanced column styling with `CellClass`, `HeaderClass`, and typography updates for better visual consistency.
| Before | After |
| -------|--------|
| ![image](https://github.com/user-attachments/assets/a989727a-5408-447e-a3f9-0d0c6358bdb1) | ![image](https://github.com/user-attachments/assets/08a881f9-3383-46c6-927f-067a29e387de) |
| Before | After |
| -------|--------|
| ![image](https://github.com/user-attachments/assets/813615c5-becb-497c-973b-ddc01f22639d) |  ![image](https://github.com/user-attachments/assets/3087b271-0877-4913-be8e-8e52f433a …

feat: add leaderboard mobile responsiveness

---

TCSA.V2026.UnitTests/Helpers/TimeSpanFormatterTests.cs
TCSA.V2026.UnitTests/TCSA.V2026.UnitTests.csproj
TCSA.V2026.sln

Introduced a new unit test project to validate the `TimeSpanFormatter` functionality.
- Added unit tests for `TimeSpanFormatter.FormatDurationOpen`.  
- Configured the test project with `.NET 9.0` and `NUnit`.  
- Integrated the new test project into the solution.

test: add unit tests

---

TCSA.V2026.UnitTests/Helpers/UserDisplayNameHelperTests.cs
TCSA.V2026/Helpers/UserDisplayNameHelper.cs
TCSA.V2026/Services/LeaderboardService.cs

This PR introduces a reusable helper and updates leaderboard logic to ensure user display names are correctly shown.
- Added `UserDisplayNameHelper` with `GetDisplayName` method for determining user display names.  
- Added unit tests for `GetDisplayName` covering various scenarios.  
- Updated `LeaderboardService` to use this helper in `UserReviewLeaderboardDisplay` and `UserLeaderboardDisplay`

fix: ensure display name is shown on leaderboard

---

TCSA.V2026/Components/Pages/Dashboard/PeerReviews.razor

Replaced the table-based layout with a card-based layout for better visual presentation and user experience.
- Replaced `<MudDataGrid>` with `<MudStack>` and `<MudPaper>` for a card-like project display.  
- Enhanced project cards with icons, styled details, conditional duration styling, and a reward section. 
- Removed `_durationCellStyleFunc` as inline conditional styling is now applied.

refactor: update project display to card-based layout

---

TCSA.V2026/Components/Pages/Dashboard/Challenges.razor

This PR introdues a new layout for displaying challenges, replacing the previous data grid. This update also adds a new section for displaying completed challenges, streaks and XP points.
- Included a button for toggling completed challenges (functionality to be implemented later).
- Added a dropdown for filtering challenges by level (functionality to be implemented later).
- Replaced the data grid with a stripe-based layout.
- Created a new section to showcase completed challenges, streaks and XP earned.

feat: improve styling of challenges page

---

TCSA.V2026/Components/UI/TCSANotificationDialog.razor

This PR improves the notification display. If no notifications are present, a friendly message is displayed to inform the user.
- `TCSANotificationDialog.razor`: Added conditional check for `Notifications` and a message for empty notifications.

feat: show friendly message when there are no notifications

---

TCSA.V2026/Components/Pages/ProjectPage.razor

This pull request fixes the text color issue in dark mode on the project pages.
- Added `Color.Default` to multiple `<MudList>` components in `ProjectPage.razor`.
- Removed `Style="color: black;"` from `<MudText>` components within lists in `ProjectPage.razor`.

fix: correct text color in dark mode on project pages

---

TCSA.V2026/Components/Pages/Articles.razor

This PR refactors the article cards by removing the button and making the entire card clickable. It also increases the shadow around the card to improve its visual prominence.
- Removed the button from the article cards.
- Made the entire card clickable.
- Increased the card’s shadow to make it stand out better against the background.

refactor: update article cards interaction and styling

---

TCSA.V2026/Components/Account/Pages/Login.razor

The pull request improves login form layout by replacing `<MudGrid>` and `<MudItem>` components with a more organized `<MudStack>` structure, enhancing visual clarity and responsiveness.
- Updated layout to use `<MudStack>` for better organization and spacing.
- Simplified links for password recovery and registration.
- Adjusted placement of "OR" text and GitHub login section within the new layout.

refactor: streamline login layout with MudStack components for better responsiveness

---

TCSA.V2026/Components/Account/Pages/Register.razor

The pull request improves register form layout by replacing `<MudGrid>` and `<MudItem>` components with a more organized `<MudStack>` structure, enhancing visual clarity and responsiveness.
- Updated layout to use <MudStack> for better organization and spacing.
- Adjusted placement of "OR" text and GitHub login section within the new layout.

refactor: streamline register layout with MudStack components for better responsiveness

---

TCSA.V2026/Data/Curriculum/CourseHelper.cs

This pull request adds the formatting for inline code text in DI course
- added `inline-code` class to all `<code>` tags so now they are `<code class='inline-code'>`

style: add inline-code class to HTML code tags

---

TCSA.V2026/Components/Pages/Dashboard/CourseDetail.razor

This pull request adjusts course image sizing to ensure proper display on mobile devices.
- `CourseDetail.razor`: Changed padding from `px-20` to `px-5 px-sm-20` for better responsiveness on mobile devices.
Before | After
------- | -----

fix: adjust course image sizing on mobile devices

---

TCSA.V2026/Components/Layout/MainLayout.razor
TCSA.V2026/Components/Pages/Dashboard/CourseDetail.razor

This pull request enhances the color palette by adding new success color properties and adjusts text color on course details page by using CSS variable with color from the palette.
- `MainLayout.razor`: Added `SuccessLighten` properties to both `PaletteLight` and `PaletteDark`.
- `CourseDetail.razor`: Updated `MudListItem` background color to use a CSS variable instead of a hardcoded value.

fix: adjust text color on course details page

---

TCSA.V2026/Components/Pages/Dashboard/Challenges.razor

This pull request enhances the visual presentation and responsiveness of challenge items by adjusting padding and adding responsive breakpoint.
- Reduced padding in `MudPaper` from `py-3 px-4 px-md-5` to `py-2 px-2 px-sm-5`.
- Added `Breakpoint` property to `MudStack` for improved responsiveness.

refactor: improve layout and responsiveness of challenge items

---

TCSA.V2026/Components/Pages/ArticlePage.razor

Removed text-decoration: underline styling from ArticlePage.
Issue #157

fix/#157-Removed text-decoration: underline styling from ArticlePage

---

TCSA.V2026/wwwroot/css/site.css

Setting the text-align to center in .jumbotron-overlay fixes the issue with the SQL challenges and should prevent this from happening again with new projects.

Fixed Issue #176

---

TCSA.V2026/Data/Curriculum/Courses/WebApiCourse.cs

In the Get Flight by Id section of article 8 covering Service Implementation of the Web API Course, a ternary expression was being used to return the savedFlight entity or null depending on the value of savedFlight which was unnecessary as it can be refactored into a simple return statement achieving the same result.
The necessary changes were also made to the accompanying paragraph.

Change ternary operatory to a simple return statement for returning the savedFlight entity

---

TCSA.V2026/Components/UI/TCSASubmitProjectDialog.razor

This pull request updates the `TCSASubmitProjectDialog.razor` to show current address when updating pull request url.
- `TCSASubmitProjectDialog.razor`: Introduced the `OnParametersSet` method to initialize `GithubUrl`.
https://github.com/user-attachments/assets/8b19a015-2546-48db-884f-5e877f634cf9

fix: show current address when updating pull request url

---

TCSA.V2026/Components/Pages/Dashboard/Community.razor

This pull request fixes an issue where submitting a PR on the Community page stopped working after introducing changes to show the current address when updating a PR’s url in the dashboard.
- `Community.razor`: Included a new `User` parameter in the `DialogParameters` for the `SubmitToReviewDialog` method.

fix: restore PR submission on Community page

---

TCSA.V2026/Services/CommunityService.cs

This pull request fixes an error that occurred when submitting community issues while no issues were present in the database.
- `CommunityService.cs`: Changed `LastAsync()` with `LastOrDefaultAsync()` to safely retrieve the last issue.
- `CommunityService.cs`: Introduced `nextProjectId` for more reliable project ID assignment.

fix: handle case with no issues

---

TCSA.V2026/Components/Layout/MainLayout.razor

This pull request replaces `MudIconButton` components with `MudLink` components in `MainLayout.razor` to enhance semantic navigation and accessibility for external links.
- Replaced buttons for Discord, YouTube, and LinkedIn with links that include accessibility attributes.
- Added `aria-hidden` to indicate that the icons are decorative and should be ignored by screen readers.

refactor: replace button icons with accessible links
